
    create table Contacto (
        id bigint not null,
        valor varchar(255),
        Contacto bigint,
        organizacion_id bigint,
        primary key (id)
    )

    create table DatoActividad (
        id bigint not null,
        anual integer not null,
        consumo integer not null,
        mes integer,
        periodicidad integer,
        tipo_consumo_id bigint,
        organizacion_id bigint,
        primary key (id)
    )

    create table Direccion (
        id bigint not null,
        altura varchar(255),
        calle varchar(255),
        localidad varchar(255),
        provincia varchar(255),
        primary key (id)
    )

    create table Estacion (
        id bigint not null,
        latitud double not null,
        longitud double not null,
        recorrido_id bigint,
        primary key (id)
    )

    create table Linea (
        id bigint not null,
        tipoLinea integer,
        tipoDeConsumo_id bigint,
        primary key (id)
    )

    create table MedioEmail (
        id bigint not null,
        primary key (id)
    )

    create table MedioWhatsApp (
        id bigint not null,
        primary key (id)
    )

    create table Organizacion (
        id bigint not null,
        clasificacion varchar(255),
        razonSocial varchar(255),
        tipo_de_organizacion varchar(255),
        direccion_id bigint,
        primary key (id)
    )

    create table Postulante (
        id bigint not null,
        miembro_id bigint,
        sector_id bigint,
        organizacion_id bigint,
        primary key (id)
    )

    create table Recorrido (
        id bigint not null,
        nombre varchar(255),
        linea_id bigint,
        primary key (id)
    )

    create table Sector (
        id bigint not null,
        name varchar(255),
        organizacion_id bigint,
        primary key (id)
    )

    create table Sector_miembros (
        Sector_id bigint not null,
        miembros_id bigint not null
    )

    create table agentes_sectoriales (
        id bigint not null,
        apellido varchar(255),
        nombre varchar(255),
        nroDocumento integer,
        tipo_documento varchar(255),
        direccion_id bigint,
        zona_id bigint,
        primary key (id)
    )

    create table bicicletas (
        id bigint not null,
        direccion_llegada_id bigint not null,
        direccion_origen_id bigint not null,
        primary key (id)
    )

    create table factores_emision (
        factor_emision_id bigint generated by default as identity (start with 1),
        factor float,
        unidad varchar(255),
        primary key (factor_emision_id)
    )

    create table historiales_huella_carbono (
        id bigint not null,
        fecha date,
        hcReportado double not null,
        organizacion_id bigint,
        zona_id bigint,
        primary key (id)
    )

    create table miembros (
        id bigint not null,
        apellido varchar(255),
        nombre varchar(255),
        nroDocumento integer,
        tipoDocumento varchar(255),
        direccion_id bigint,
        primary key (id)
    )

    create table pies (
        id bigint not null,
        direccion_llegada_id bigint,
        direccion_origen_id bigint,
        primary key (id)
    )

    create table servicios_contratados (
        id bigint not null,
        nombre varchar(255),
        tipo_servicio_contratado varchar(255),
        primary key (id)
    )

    create table tipos_consumos (
        tipo_consumo_id bigint not null,
        actividad integer,
        alcance integer,
        nombre varchar(255),
        unidad integer,
        primary key (tipo_consumo_id)
    )

    create table tramos (
        id bigint not null,
        organizacion_id bigint,
        transporte_id bigint,
        trayecto_id bigint,
        primary key (id)
    )

    create table transportes_contratados (
        id bigint not null,
        direccion_origen_id bigint not null,
        direccion_llegada_id bigint not null,
        servicio_contratado_id bigint not null,
        tipo_consumo_id bigint not null,
        primary key (id)
    )

    create table transportes_publicos (
        id bigint not null,
        estacionFinal_id bigint,
        estacionInicial_id bigint,
        linea_id bigint,
        primary key (id)
    )

    create table trayectos (
        id bigint not null,
        fecha date,
        miembro_id bigint,
        primary key (id)
    )

    create table usuarios (
        usuario_id bigint generated by default as identity (start with 1),
        contrasenia varchar(255),
        nombre_usuario varchar(255),
        tipo_usuario varchar(255),
        primary key (usuario_id)
    )

    create table vehiculos_particulares (
        id bigint not null,
        tipo_combustible varchar(255),
        tipo_vehiculo varchar(255),
        direccion_origen_id bigint not null,
        direccion_llegada_id bigint not null,
        tipo_consumo_id bigint not null,
        primary key (id)
    )

    create table zonas (
        id bigint not null,
        nombreProvinciaLocalidad varchar(255),
        tipo_zona varchar(255),
        primary key (id)
    )

    alter table Contacto 
        add constraint FK_7r117ujoxonqhyj6to4npqss 
        foreign key (organizacion_id) 
        references Organizacion

    alter table DatoActividad 
        add constraint FK_ayfn14iyasidsn13m63msua1j 
        foreign key (tipo_consumo_id) 
        references tipos_consumos

    alter table DatoActividad 
        add constraint FK_iwped1jotk3ffy9ygpyan1ad 
        foreign key (organizacion_id) 
        references Organizacion

    alter table Estacion 
        add constraint FK_fxukeeh8i5gcmh4d9eg9wsu98 
        foreign key (recorrido_id) 
        references Recorrido

    alter table Linea 
        add constraint FK_1el5cw8q627j0mcosytnjj41y 
        foreign key (tipoDeConsumo_id) 
        references tipos_consumos

    alter table Organizacion 
        add constraint FK_a35a7d9wbmnh6jfplurvv8n4d 
        foreign key (direccion_id) 
        references Direccion

    alter table Postulante 
        add constraint FK_tm8gwpha8sjgpg4f5c6cnj6l1 
        foreign key (miembro_id) 
        references miembros

    alter table Postulante 
        add constraint FK_9d0jyio6c2uclj265b68hfrj0 
        foreign key (sector_id) 
        references Sector

    alter table Postulante 
        add constraint FK_h50nprnk17uo7ofy7m4qoe6k1 
        foreign key (organizacion_id) 
        references Organizacion

    alter table Recorrido 
        add constraint FK_8iyt394ymv14locg294jmjq6r 
        foreign key (linea_id) 
        references Linea

    alter table Sector 
        add constraint FK_sb9xwaiuxouphx7ju2ej3fnxq 
        foreign key (organizacion_id) 
        references Organizacion

    alter table Sector_miembros 
        add constraint FK_1d4ctmus3y47lyayxcbh5vufl 
        foreign key (miembros_id) 
        references miembros

    alter table Sector_miembros 
        add constraint FK_lmup5iyg5jjbwvg8o972tbrtp 
        foreign key (Sector_id) 
        references Sector

    alter table agentes_sectoriales 
        add constraint FK_37qybtakouycy1e3eyyngot5o 
        foreign key (direccion_id) 
        references Direccion

    alter table agentes_sectoriales 
        add constraint FK_375qsy7ejxi9vtoogr8xfvfpp 
        foreign key (zona_id) 
        references zonas

    alter table bicicletas 
        add constraint FK_drvo0ymqxhmwnccjdxgnxwtrh 
        foreign key (direccion_llegada_id) 
        references Direccion

    alter table bicicletas 
        add constraint FK_bfot4byigvqbr186n7sqewni3 
        foreign key (direccion_origen_id) 
        references Direccion

    alter table historiales_huella_carbono 
        add constraint FK_pailmwd4n9ctaukren0tr22fs 
        foreign key (organizacion_id) 
        references Organizacion

    alter table historiales_huella_carbono 
        add constraint FK_p65qac65gegurvfoooif1baqs 
        foreign key (zona_id) 
        references zonas

    alter table miembros 
        add constraint FK_cctk8w6j1ob0djem8scecu26j 
        foreign key (direccion_id) 
        references Direccion

    alter table pies 
        add constraint FK_ebeg9tvypnja9ieatk6uiyt3o 
        foreign key (direccion_llegada_id) 
        references Direccion

    alter table pies 
        add constraint FK_bijk1rm5sp51imyayv01vxkc6 
        foreign key (direccion_origen_id) 
        references Direccion

    alter table tramos 
        add constraint FK_2y4qxxndxkpwwciyrbjm2tqbc 
        foreign key (organizacion_id) 
        references Organizacion

    alter table tramos 
        add constraint FK_ghpgminsqvybsssyv0fg1kwj6 
        foreign key (trayecto_id) 
        references trayectos

    alter table transportes_contratados 
        add constraint FK_37r1b57xnwad2vidf5rdshd7p 
        foreign key (direccion_origen_id) 
        references Direccion

    alter table transportes_contratados 
        add constraint FK_gohbac6oqmm6t1utk4k3528st 
        foreign key (direccion_llegada_id) 
        references Direccion

    alter table transportes_contratados 
        add constraint FK_ad0qjy5ghi1m8adatgof68ims 
        foreign key (servicio_contratado_id) 
        references servicios_contratados

    alter table transportes_contratados 
        add constraint FK_bccq3fm7420k7htn2j8r38owt 
        foreign key (tipo_consumo_id) 
        references tipos_consumos

    alter table transportes_publicos 
        add constraint FK_p2ybcj7wl6swk9514s0tdesvf 
        foreign key (estacionFinal_id) 
        references Estacion

    alter table transportes_publicos 
        add constraint FK_bner230qosln1ij4i9ldv8ai9 
        foreign key (estacionInicial_id) 
        references Estacion

    alter table transportes_publicos 
        add constraint FK_3lyiryi2qc5h9vss9cvvpy0l6 
        foreign key (linea_id) 
        references Linea

    alter table trayectos 
        add constraint FK_e2s5gnqbk4u6e487lpiumusu6 
        foreign key (miembro_id) 
        references miembros

    alter table vehiculos_particulares 
        add constraint FK_nhs2fslgw2ym6hr2d8j6n31le 
        foreign key (direccion_origen_id) 
        references Direccion

    alter table vehiculos_particulares 
        add constraint FK_nbf6t4ktk8oynloouscpqt2d 
        foreign key (direccion_llegada_id) 
        references Direccion

    alter table vehiculos_particulares 
        add constraint FK_auq5p8o94r35jtnx75cpgj7rj 
        foreign key (tipo_consumo_id) 
        references tipos_consumos

    create table hibernate_sequences (
         sequence_name varchar(255),
         sequence_next_hi_value integer 
    )
